# Generated by Django 4.0.8 on 2022-12-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('transaction_type', models.CharField(max_length=250)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
